services:
  nginx:
    image: nginx:tdesous
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443" # To HTTPS
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
  mariadb:
    image: mariadb:tdesous
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
    entrypoint: /config-mariadb.sh
  wordpress:
    image: wordpress:tdesous
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
    env_file:
      - .env
    entrypoint: ./config-wordpress.sh


volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: ~/data/mariadb # checkar com makefile, subject
      o: bind
      type: none
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: ~/data/wordpress # checkar com makefile, subject
      o: bind
      type: none

networks:
  inception:
    name: inception